version: "3.8"

services:
  node1:
    image: besu-image-local:25.10.0
    container_name: node-besu1
    network_mode: "host"
    command: >
      --data-path=/opt/besu/data
      --genesis-file=/opt/besu/genesis.json
      --rpc-http-enabled
      --host-allowlist="*"
      --rpc-http-cors-origins="all"
      --profile=ENTERPRISE
      --metrics-enabled
      --rpc-http-host=0.0.0.0
      --rpc-http-api=WEB3,ETH,NET,TRACE,DEBUG,ADMIN,TXPOOL,PERM,QBFT
      --rpc-ws-api=WEB3,ETH,NET,TRACE,DEBUG,ADMIN,TXPOOL,PERM,QBFT
      --data-storage-format=BONSAI 
      --tx-pool-min-gas-price=0 
      --min-gas-price=0 
      --rpc-ws-enabled=true 
      --rpc-ws-port=8645 
      --tx-pool-limit-by-account-percentage=1 
      --tx-pool-max-size=4096 
      --metrics-port=9545
      --p2p-port=30303
      --rpc-http-port=8545
      --permissions-accounts-config-file-enabled
      --permissions-nodes-config-file-enabled
    volumes:
      - ./Permissioned-Network/genesis.json:/opt/besu/genesis.json
      - ./Permissioned-Network/Node-1/data:/opt/besu/data
 
  node2:
    image: besu-image-local:25.10.0
    container_name: node-besu2
    network_mode: "host"
    command: >
      --data-path=/opt/besu/data
      --genesis-file=/opt/besu/genesis.json
      --bootnodes=enode://def2f22894b99173fe042a160494c6e8760241231c0daa78bc227136f624e8fd15f250391eb00a3e535548acc978de5feeff19eb78ccb085f8f7ef88d0fd8690@127.0.0.1:30303,enode://0c20477e0a34dc4fd2d409d18ff6bc3ae5c9401460fdc6c52bc8361b68b0f06f555183e6bc01d7c1b3b18b18e02d110b9e27cfca89b283791e936a288814f44b@127.0.0.1:30305
      --rpc-http-enabled
      --host-allowlist="*"
      --rpc-http-cors-origins="all"
      --profile=ENTERPRISE
      --metrics-enabled
      --rpc-http-host=0.0.0.0
      --rpc-http-api=WEB3,ETH,NET,TRACE,DEBUG,ADMIN,TXPOOL,PERM,QBFT
      --rpc-ws-api=WEB3,ETH,NET,TRACE,DEBUG,ADMIN,TXPOOL,PERM,QBFT
      --data-storage-format=BONSAI 
      --tx-pool-min-gas-price=0 
      --min-gas-price=0 
      --rpc-ws-enabled=true 
      --rpc-ws-port=8646 
      --tx-pool-limit-by-account-percentage=1 
      --tx-pool-max-size=4096 
      --metrics-port=9546
      --p2p-port=30304
      --rpc-http-port=8546
      --permissions-accounts-config-file-enabled
      --permissions-nodes-config-file-enabled
    volumes:
      - ./Permissioned-Network/genesis.json:/opt/besu/genesis.json
      - ./Permissioned-Network/Node-2/data:/opt/besu/data

  node3:
    image: besu-image-local:25.10.0
    container_name: node-besu3
    network_mode: "host"
    command: >
      --data-path=/opt/besu/data
      --genesis-file=/opt/besu/genesis.json
      --rpc-http-enabled
      --host-allowlist="*"
      --rpc-http-cors-origins="all"
      --profile=ENTERPRISE
      --metrics-enabled
      --rpc-http-host=0.0.0.0
      --rpc-http-api=WEB3,ETH,NET,TRACE,DEBUG,ADMIN,TXPOOL,PERM,QBFT
      --rpc-ws-api=WEB3,ETH,NET,TRACE,DEBUG,ADMIN,TXPOOL,PERM,QBFT
      --data-storage-format=BONSAI 
      --tx-pool-min-gas-price=0 
      --min-gas-price=0 
      --rpc-ws-enabled=true 
      --rpc-ws-port=8647 
      --tx-pool-limit-by-account-percentage=1 
      --tx-pool-max-size=4096 
      --metrics-port=9547
      --p2p-port=30305
      --rpc-http-port=8547
      --permissions-accounts-config-file-enabled
      --permissions-nodes-config-file-enabled
    volumes:
      - ./Permissioned-Network/genesis.json:/opt/besu/genesis.json
      - ./Permissioned-Network/Node-3/data:/opt/besu/data

  node4:
    image: besu-image-local:25.10.0
    container_name: node-besu4
    network_mode: "host"
    command: >
      --data-path=/opt/besu/data
      --genesis-file=/opt/besu/genesis.json
      --bootnodes=enode://def2f22894b99173fe042a160494c6e8760241231c0daa78bc227136f624e8fd15f250391eb00a3e535548acc978de5feeff19eb78ccb085f8f7ef88d0fd8690@127.0.0.1:30303,enode://0c20477e0a34dc4fd2d409d18ff6bc3ae5c9401460fdc6c52bc8361b68b0f06f555183e6bc01d7c1b3b18b18e02d110b9e27cfca89b283791e936a288814f44b@127.0.0.1:30305
      --rpc-http-enabled
      --host-allowlist="*"
      --rpc-http-cors-origins="all"
      --profile=ENTERPRISE
      --metrics-enabled
      --rpc-http-host=0.0.0.0
      --rpc-http-api=WEB3,ETH,NET,TRACE,DEBUG,ADMIN,TXPOOL,PERM,QBFT
      --rpc-ws-api=WEB3,ETH,NET,TRACE,DEBUG,ADMIN,TXPOOL,PERM,QBFT
      --data-storage-format=BONSAI 
      --tx-pool-min-gas-price=0 
      --min-gas-price=0 
      --rpc-ws-enabled=true 
      --rpc-ws-port=8648 
      --tx-pool-limit-by-account-percentage=1 
      --tx-pool-max-size=4096 
      --metrics-port=9548
      --p2p-port=30306
      --rpc-http-port=8548
      --permissions-accounts-config-file-enabled
      --permissions-nodes-config-file-enabled
    volumes:
      - ./Permissioned-Network/genesis.json:/opt/besu/genesis.json
      - ./Permissioned-Network/Node-4/data:/opt/besu/data

  node5:
    image: besu-image-local:25.10.0
    container_name: node-besu5
    network_mode: "host"
    command: >
      --data-path=/opt/besu/data
      --genesis-file=/opt/besu/genesis.json
      --bootnodes=enode://def2f22894b99173fe042a160494c6e8760241231c0daa78bc227136f624e8fd15f250391eb00a3e535548acc978de5feeff19eb78ccb085f8f7ef88d0fd8690@127.0.0.1:30303,enode://0c20477e0a34dc4fd2d409d18ff6bc3ae5c9401460fdc6c52bc8361b68b0f06f555183e6bc01d7c1b3b18b18e02d110b9e27cfca89b283791e936a288814f44b@127.0.0.1:30305
      --rpc-http-enabled
      --host-allowlist="*"
      --rpc-http-cors-origins="all"
      --profile=ENTERPRISE
      --metrics-enabled
      --rpc-http-host=0.0.0.0
      --rpc-http-api=WEB3,ETH,NET,TRACE,DEBUG,ADMIN,TXPOOL,PERM,QBFT
      --rpc-ws-api=WEB3,ETH,NET,TRACE,DEBUG,ADMIN,TXPOOL,PERM,QBFT
      --data-storage-format=BONSAI 
      --tx-pool-min-gas-price=0 
      --min-gas-price=0 
      --rpc-ws-enabled=true 
      --rpc-ws-port=8649 
      --tx-pool-limit-by-account-percentage=1 
      --tx-pool-max-size=4096 
      --metrics-port=9549
      --p2p-port=30307
      --rpc-http-port=8549
      --permissions-accounts-config-file-enabled
      --permissions-nodes-config-file-enabled
    volumes:
      - ./Permissioned-Network/genesis.json:/opt/besu/genesis.json
      - ./Permissioned-Network/Node-5/data:/opt/besu/data

  node6:
    image: besu-image-local:25.10.0
    container_name: node-besu6
    network_mode: "host"
    command: >
      --data-path=/opt/besu/data
      --genesis-file=/opt/besu/genesis.json
      --bootnodes=enode://def2f22894b99173fe042a160494c6e8760241231c0daa78bc227136f624e8fd15f250391eb00a3e535548acc978de5feeff19eb78ccb085f8f7ef88d0fd8690@127.0.0.1:30303,enode://0c20477e0a34dc4fd2d409d18ff6bc3ae5c9401460fdc6c52bc8361b68b0f06f555183e6bc01d7c1b3b18b18e02d110b9e27cfca89b283791e936a288814f44b@127.0.0.1:30305
      --rpc-http-enabled
      --host-allowlist="*"
      --rpc-http-cors-origins="all"
      --profile=ENTERPRISE
      --metrics-enabled
      --rpc-http-host=0.0.0.0
      --rpc-http-api=WEB3,ETH,NET,TRACE,DEBUG,ADMIN,TXPOOL,PERM,QBFT
      --rpc-ws-api=WEB3,ETH,NET,TRACE,DEBUG,ADMIN,TXPOOL,PERM,QBFT
      --data-storage-format=BONSAI 
      --tx-pool-min-gas-price=0 
      --min-gas-price=0 
      --rpc-ws-enabled=true 
      --rpc-ws-port=8650
      --tx-pool-limit-by-account-percentage=1 
      --tx-pool-max-size=4096 
      --metrics-port=9550
      --p2p-port=30308
      --rpc-http-port=8550
      --permissions-accounts-config-file-enabled
      --permissions-nodes-config-file-enabled
    volumes:
      - ./Permissioned-Network/genesis.json:/opt/besu/genesis.json
      - ./Permissioned-Network/Node-6/data:/opt/besu/data

networks:
  default:
    name: besu-network
    external: true